backend:
  name: github
  accept_roles: #optional - accepts all users if left out
    - root
  repo: 'jeremyosz/brickLX'
media_folder: 'static/uploads' # Media files will be stored in the repo under static/images/uploads
public_folder: 'uploads' # The src attribute for uploaded media will begin with /images/uploads
collections:
  - label: "Featured Project"
    name: "FeturedProject"
    widget: "object"
    allow add: true
    folder: 'src/content/featured'
    create: true
    identifier_field: 'projID'
    fields:
      - label: "Project"
        name: "relFeaturedPoject"
        widget: "relation"
        collection: "Projeccts"
        searchFields: ["name", "projId"]
        displayFields: ["name", "projId"]
        valueField: "projId"
        multiple: false
  - label: "Projects"
    name: "Projects"
    widget: "object"
    allow add: true
    folder: 'src/content/projects'
    create: true
    identifier_field: 'projId'
    fields:
      - {label: Title, name: projTitle, widget: string}
      - {label: Project ID, name: projId, widget: string, required: true}
      - label: Image 
        name: imageTest 
        widget: list 
        fields:
          - {label: Caption, name: caption, widget: string}
          - {label: "Image", name: "src", widget: "image", required: true}